sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: h7hkOLhvuuisXa21t3ufJPekcMo3ZthCkoBT0pK9Br+g1V5ErzfJs4dqp0bV+cI/Vw3laMhmvuLRdeHOIgIwQ4fzRwxkD5Sv0lg3OYV2xwJ19dFSOu9e+fSjnUkECv58hWwqLoyELhHB6uXJ5ryFL9bTXSAOtX9BH90s5BS5o2LNrVe+dOFg39odw87rw0j+Z4nklEYg84VCn9EJTGK+Ztwi7luk3A6+XsHY67YgqwjLSvScSG2es/omWufj88myr0F6KcHCcWDrZFWDFQ0EM7+H8b9NMb5RVsmNWhETpxDPNYSWQcJpQh8/0yCESV4+0J6FN3pXIuaspzTrboGhHgMz79F70/Xnndtt/tjz0N9Jg1afNDGeN1ZucwaxPoMZEKng74UtSJbolcYMZF6A0k+PVSOM4dPOe/sBvGEFZfLoQzhE7FUOj5jebmzUp9Uwp0dHtMul01B1bNJpb941Ka6J3w8aiHsNbUoiTx6Nc5PMVl+/fmypHlhUe8d2JYIoSsRX7UgFO9gJ2LbhPVs9mQEwDoiBV2yArV/ML9fzA26z49n6l4iNoJvi4eFfNeBJDpVXkkNjwh3fImrxWLDHUh8PDC4aSwLE5aixnGahHyJaj8lGDdgSYsBiRZRDhqIvwlrLz65lhFQlNRMd2QUOvb9VN0r4frTdQAU3GVxvfMo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Reina-Valera-New-Testament-of-the-Bible-1909_5881
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy